POSTGRES_USER := $(shell grep -E '^POSTGRES_USER=' .env 2>/dev/null | cut -d= -f2 | xargs)
POSTGRES_DB   := $(shell grep -E '^POSTGRES_DB=' .env 2>/dev/null | cut -d= -f2 | xargs)
POSTGRES_USER := $(if $(POSTGRES_USER),$(POSTGRES_USER),todo)
POSTGRES_DB   := $(if $(POSTGRES_DB),$(POSTGRES_DB),todo_app)

.DEFAULT_GOAL := help
.PHONY: help up up-logs down reset logs logs-backend logs-frontend logs-db ps \
        shell-backend shell-db migrate migration install-frontend \
        lint-frontend typecheck-frontend test-backend test-frontend \
        test-frontend-coverage test-e2e test clean

help: ## Show this help message
	@echo "Available targets:"
	@awk 'BEGIN {FS = ":.*##"} /^[a-zA-Z0-9_-]+:.*##/ { printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2 }' $(MAKEFILE_LIST)

up: ## Start the full stack (detached, auto-build)
	docker compose up -d --build

up-logs: ## Start the stack in the foreground with live logs
	docker compose up --build

down: ## Stop containers (preserves data volumes)
	docker compose down

reset: ## Stop containers AND wipe all data volumes (DESTRUCTIVE)
	docker compose down -v

logs: ## Tail logs from all services
	docker compose logs -f

logs-backend: ## Tail logs from the backend service
	docker compose logs -f backend

logs-frontend: ## Tail logs from the frontend service
	docker compose logs -f frontend

logs-db: ## Tail logs from the db service
	docker compose logs -f db

ps: ## Show service status
	docker compose ps

shell-backend: ## Interactive /bin/sh inside the backend container
	docker compose exec backend /bin/sh

shell-db: ## psql shell inside the db container
	docker compose exec db psql -U $(POSTGRES_USER) -d $(POSTGRES_DB)

migrate: ## Run Alembic upgrade head (apply pending migrations)
	docker compose exec backend alembic upgrade head

migration: ## Generate an autogenerated migration (usage: make migration name="add users")
	@if [ -z "$(name)" ]; then echo "Error: name is required. Usage: make migration name=\"<description>\""; exit 1; fi
	docker compose exec backend alembic revision --autogenerate -m "$(name)"

install-frontend: ## Run pnpm install in frontend/ (regenerate lockfile after package.json edits)
	cd frontend && pnpm install

lint-frontend: ## Run ESLint inside the frontend container
	docker compose exec frontend pnpm lint

typecheck-frontend: ## Run tsc --noEmit inside the frontend container
	docker compose exec frontend pnpm typecheck

test-backend: ## Run pytest inside the backend container
	docker compose exec backend pytest -q

test-frontend: ## Run vitest (unit + component tests) inside the frontend container
	docker compose exec frontend pnpm test

test-frontend-coverage: ## Run vitest with v8 coverage (enforces 70% thresholds)
	docker compose exec frontend pnpm test:coverage

test-e2e: ## Run Playwright E2E + axe-core suite on host (stack must be up: make up)
	cd frontend && pnpm test:e2e

test: test-backend test-frontend test-e2e ## Run backend, frontend, and E2E suites in sequence

clean: ## Wipe containers, volumes, and locally-built images (DESTRUCTIVE)
	docker compose down -v --rmi local

clean-volumes: ## Wipe only data volumes (DESTRUCTIVE)
	docker compose down -v

clean-everything: ## Wipe ALL containers, volumes, and images (DANGEROUS)
	docker system prune -a --volumes --force