from sqlmodel import SQLModel

# Configure naming convention for Alembic autogenerate (Retro T1).
# This ensures autogenerated migrations produce predictable constraint names
# such as idx_todos_user_id without manual renaming.
SQLModel.metadata.naming_convention = {
    "ix": "idx_%(table_name)s_%(column_0_name)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

from app.models.user import User  # noqa: F401, E402  -- Story 2.1
from app.models.todo import Todo  # noqa: F401, E402  -- Story 3.1
from app.models.category import Category  # noqa: F401, E402  -- Story 5.1

# These imports populate SQLModel.metadata so Alembic autogenerate detects them.
